// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/stockyard.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VmEnv             map[string]string      `protobuf:"bytes,3,rep,name=vm_env,json=vmEnv,proto3" json:"vm_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // VM-level env injected via cloud-init
	Cpus              int32                  `protobuf:"varint,4,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory            string                 `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	NoTailscale       bool                   `protobuf:"varint,6,opt,name=no_tailscale,json=noTailscale,proto3" json:"no_tailscale,omitempty"`
	TailscaleAuthKey  string                 `protobuf:"bytes,7,opt,name=tailscale_auth_key,json=tailscaleAuthKey,proto3" json:"tailscale_auth_key,omitempty"`    // Optional: override 1Password lookup
	SshAuthorizedKeys []string               `protobuf:"bytes,8,rep,name=ssh_authorized_keys,json=sshAuthorizedKeys,proto3" json:"ssh_authorized_keys,omitempty"` // SSH public keys for VM access
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_stockyard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetVmEnv() map[string]string {
	if x != nil {
		return x.VmEnv
	}
	return nil
}

func (x *CreateTaskRequest) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *CreateTaskRequest) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *CreateTaskRequest) GetNoTailscale() bool {
	if x != nil {
		return x.NoTailscale
	}
	return false
}

func (x *CreateTaskRequest) GetTailscaleAuthKey() string {
	if x != nil {
		return x.TailscaleAuthKey
	}
	return ""
}

func (x *CreateTaskRequest) GetSshAuthorizedKeys() []string {
	if x != nil {
		return x.SshAuthorizedKeys
	}
	return nil
}

type CreateTaskResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TailscaleHostname string                 `protobuf:"bytes,2,opt,name=tailscale_hostname,json=tailscaleHostname,proto3" json:"tailscale_hostname,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_api_stockyard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskResponse) GetTailscaleHostname() string {
	if x != nil {
		return x.TailscaleHostname
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_stockyard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_stockyard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_stockyard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_stockyard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type StopTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskRequest) Reset() {
	*x = StopTaskRequest{}
	mi := &file_api_stockyard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskRequest) ProtoMessage() {}

func (x *StopTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskRequest.ProtoReflect.Descriptor instead.
func (*StopTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{6}
}

func (x *StopTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type StopTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskResponse) Reset() {
	*x = StopTaskResponse{}
	mi := &file_api_stockyard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskResponse) ProtoMessage() {}

func (x *StopTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskResponse.ProtoReflect.Descriptor instead.
func (*StopTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{7}
}

type RestartTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTaskRequest) Reset() {
	*x = RestartTaskRequest{}
	mi := &file_api_stockyard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTaskRequest) ProtoMessage() {}

func (x *RestartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTaskRequest.ProtoReflect.Descriptor instead.
func (*RestartTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{8}
}

func (x *RestartTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RestartTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTaskResponse) Reset() {
	*x = RestartTaskResponse{}
	mi := &file_api_stockyard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTaskResponse) ProtoMessage() {}

func (x *RestartTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTaskResponse.ProtoReflect.Descriptor instead.
func (*RestartTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{9}
}

type DestroyTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyTaskRequest) Reset() {
	*x = DestroyTaskRequest{}
	mi := &file_api_stockyard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyTaskRequest) ProtoMessage() {}

func (x *DestroyTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyTaskRequest.ProtoReflect.Descriptor instead.
func (*DestroyTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{10}
}

func (x *DestroyTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DestroyTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyTaskResponse) Reset() {
	*x = DestroyTaskResponse{}
	mi := &file_api_stockyard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyTaskResponse) ProtoMessage() {}

func (x *DestroyTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyTaskResponse.ProtoReflect.Descriptor instead.
func (*DestroyTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{11}
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_api_stockyard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSnapshotRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotName  string                 `protobuf:"bytes,1,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_api_stockyard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSnapshotResponse) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_api_stockyard_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{14}
}

func (x *ListSnapshotsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*Snapshot            `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_api_stockyard_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{15}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type RestoreSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SnapshotName  string                 `protobuf:"bytes,2,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSnapshotRequest) Reset() {
	*x = RestoreSnapshotRequest{}
	mi := &file_api_stockyard_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSnapshotRequest) ProtoMessage() {}

func (x *RestoreSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RestoreSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{16}
}

func (x *RestoreSnapshotRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RestoreSnapshotRequest) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

type RestoreSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSnapshotResponse) Reset() {
	*x = RestoreSnapshotResponse{}
	mi := &file_api_stockyard_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSnapshotResponse) ProtoMessage() {}

func (x *RestoreSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSnapshotResponse.ProtoReflect.Descriptor instead.
func (*RestoreSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{17}
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	Tail          int32                  `protobuf:"varint,3,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_api_stockyard_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{18}
}

func (x *GetLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *GetLogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_stockyard_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{19}
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type Task struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TailscaleHostname string                 `protobuf:"bytes,4,opt,name=tailscale_hostname,json=tailscaleHostname,proto3" json:"tailscale_hostname,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StoppedAt         string                 `protobuf:"bytes,6,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_stockyard_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{20}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetTailscaleHostname() string {
	if x != nil {
		return x.TailscaleHostname
	}
	return ""
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Task) GetStoppedAt() string {
	if x != nil {
		return x.StoppedAt
	}
	return ""
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_api_stockyard_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{21}
}

func (x *Snapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Snapshot) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Snapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Queue management messages
type CreateQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"` // "serial" or "concurrent", default "serial"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueRequest) Reset() {
	*x = CreateQueueRequest{}
	mi := &file_api_stockyard_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueRequest) ProtoMessage() {}

func (x *CreateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueRequest.ProtoReflect.Descriptor instead.
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{22}
}

func (x *CreateQueueRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *CreateQueueRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type CreateQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueResponse) Reset() {
	*x = CreateQueueResponse{}
	mi := &file_api_stockyard_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueResponse) ProtoMessage() {}

func (x *CreateQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueResponse.ProtoReflect.Descriptor instead.
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{23}
}

type ListQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_api_stockyard_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{24}
}

func (x *ListQueuesRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ListQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*QueueInfo           `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_api_stockyard_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{25}
}

func (x *ListQueuesResponse) GetQueues() []*QueueInfo {
	if x != nil {
		return x.Queues
	}
	return nil
}

type GetQueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatusRequest) Reset() {
	*x = GetQueueStatusRequest{}
	mi := &file_api_stockyard_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatusRequest) ProtoMessage() {}

func (x *GetQueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatusRequest.ProtoReflect.Descriptor instead.
func (*GetQueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{26}
}

func (x *GetQueueStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetQueueStatusRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type GetQueueStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *QueueInfo             `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Commands      []*CommandInfo         `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatusResponse) Reset() {
	*x = GetQueueStatusResponse{}
	mi := &file_api_stockyard_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatusResponse) ProtoMessage() {}

func (x *GetQueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatusResponse.ProtoReflect.Descriptor instead.
func (*GetQueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{27}
}

func (x *GetQueueStatusResponse) GetQueue() *QueueInfo {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *GetQueueStatusResponse) GetCommands() []*CommandInfo {
	if x != nil {
		return x.Commands
	}
	return nil
}

type FlushQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushQueueRequest) Reset() {
	*x = FlushQueueRequest{}
	mi := &file_api_stockyard_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushQueueRequest) ProtoMessage() {}

func (x *FlushQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushQueueRequest.ProtoReflect.Descriptor instead.
func (*FlushQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{28}
}

func (x *FlushQueueRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FlushQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type FlushQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushQueueResponse) Reset() {
	*x = FlushQueueResponse{}
	mi := &file_api_stockyard_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushQueueResponse) ProtoMessage() {}

func (x *FlushQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushQueueResponse.ProtoReflect.Descriptor instead.
func (*FlushQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{29}
}

type DestroyQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyQueueRequest) Reset() {
	*x = DestroyQueueRequest{}
	mi := &file_api_stockyard_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyQueueRequest) ProtoMessage() {}

func (x *DestroyQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyQueueRequest.ProtoReflect.Descriptor instead.
func (*DestroyQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{30}
}

func (x *DestroyQueueRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DestroyQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type DestroyQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyQueueResponse) Reset() {
	*x = DestroyQueueResponse{}
	mi := &file_api_stockyard_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyQueueResponse) ProtoMessage() {}

func (x *DestroyQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyQueueResponse.ProtoReflect.Descriptor instead.
func (*DestroyQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{31}
}

// Command execution messages
type QueueCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StopOnFailure bool                   `protobuf:"varint,5,opt,name=stop_on_failure,json=stopOnFailure,proto3" json:"stop_on_failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueCommandRequest) Reset() {
	*x = QueueCommandRequest{}
	mi := &file_api_stockyard_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueCommandRequest) ProtoMessage() {}

func (x *QueueCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueCommandRequest.ProtoReflect.Descriptor instead.
func (*QueueCommandRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{32}
}

func (x *QueueCommandRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *QueueCommandRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *QueueCommandRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *QueueCommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *QueueCommandRequest) GetStopOnFailure() bool {
	if x != nil {
		return x.StopOnFailure
	}
	return false
}

type QueueCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueCommandResponse) Reset() {
	*x = QueueCommandResponse{}
	mi := &file_api_stockyard_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueCommandResponse) ProtoMessage() {}

func (x *QueueCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueCommandResponse.ProtoReflect.Descriptor instead.
func (*QueueCommandResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{33}
}

func (x *QueueCommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type GetCommandStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandStatusRequest) Reset() {
	*x = GetCommandStatusRequest{}
	mi := &file_api_stockyard_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandStatusRequest) ProtoMessage() {}

func (x *GetCommandStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCommandStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{34}
}

func (x *GetCommandStatusRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type GetCommandStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *CommandInfo           `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandStatusResponse) Reset() {
	*x = GetCommandStatusResponse{}
	mi := &file_api_stockyard_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandStatusResponse) ProtoMessage() {}

func (x *GetCommandStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCommandStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{35}
}

func (x *GetCommandStatusResponse) GetCommand() *CommandInfo {
	if x != nil {
		return x.Command
	}
	return nil
}

type StreamCommandOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCommandOutputRequest) Reset() {
	*x = StreamCommandOutputRequest{}
	mi := &file_api_stockyard_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCommandOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCommandOutputRequest) ProtoMessage() {}

func (x *StreamCommandOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCommandOutputRequest.ProtoReflect.Descriptor instead.
func (*StreamCommandOutputRequest) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{36}
}

func (x *StreamCommandOutputRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *StreamCommandOutputRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type CommandOutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutputChunk) Reset() {
	*x = CommandOutputChunk{}
	mi := &file_api_stockyard_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutputChunk) ProtoMessage() {}

func (x *CommandOutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutputChunk.ProtoReflect.Descriptor instead.
func (*CommandOutputChunk) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{37}
}

func (x *CommandOutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Shared info types
type QueueInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Protected     bool                   `protobuf:"varint,3,opt,name=protected,proto3" json:"protected,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueInfo) Reset() {
	*x = QueueInfo{}
	mi := &file_api_stockyard_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInfo) ProtoMessage() {}

func (x *QueueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInfo.ProtoReflect.Descriptor instead.
func (*QueueInfo) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{38}
}

func (x *QueueInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *QueueInfo) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *QueueInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CommandInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StopOnFailure bool                   `protobuf:"varint,6,opt,name=stop_on_failure,json=stopOnFailure,proto3" json:"stop_on_failure,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     string                 `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandInfo) Reset() {
	*x = CommandInfo{}
	mi := &file_api_stockyard_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInfo) ProtoMessage() {}

func (x *CommandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_stockyard_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInfo.ProtoReflect.Descriptor instead.
func (*CommandInfo) Descriptor() ([]byte, []int) {
	return file_api_stockyard_proto_rawDescGZIP(), []int{39}
}

func (x *CommandInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandInfo) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *CommandInfo) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandInfo) GetStopOnFailure() bool {
	if x != nil {
		return x.StopOnFailure
	}
	return false
}

func (x *CommandInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommandInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *CommandInfo) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

var File_api_stockyard_proto protoreflect.FileDescriptor

const file_api_stockyard_proto_rawDesc = "" +
	"\n" +
	"\x13api/stockyard.proto\x12\fstockyard.v1\"\xd7\x02\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\x06vm_env\x18\x03 \x03(\v2*.stockyard.v1.CreateTaskRequest.VmEnvEntryR\x05vmEnv\x12\x12\n" +
	"\x04cpus\x18\x04 \x01(\x05R\x04cpus\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\tR\x06memory\x12!\n" +
	"\fno_tailscale\x18\x06 \x01(\bR\vnoTailscale\x12,\n" +
	"\x12tailscale_auth_key\x18\a \x01(\tR\x10tailscaleAuthKey\x12.\n" +
	"\x13ssh_authorized_keys\x18\b \x03(\tR\x11sshAuthorizedKeys\x1a8\n" +
	"\n" +
	"VmEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03\"\\\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\x12tailscale_hostname\x18\x02 \x01(\tR\x11tailscaleHostname\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"9\n" +
	"\x0fGetTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.stockyard.v1.TaskR\x04task\"*\n" +
	"\x10ListTasksRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"=\n" +
	"\x11ListTasksResponse\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.stockyard.v1.TaskR\x05tasks\"*\n" +
	"\x0fStopTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x12\n" +
	"\x10StopTaskResponse\"-\n" +
	"\x12RestartTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x15\n" +
	"\x13RestartTaskResponse\"-\n" +
	"\x12DestroyTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x15\n" +
	"\x13DestroyTaskResponse\"F\n" +
	"\x15CreateSnapshotRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"=\n" +
	"\x16CreateSnapshotResponse\x12#\n" +
	"\rsnapshot_name\x18\x01 \x01(\tR\fsnapshotName\"/\n" +
	"\x14ListSnapshotsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"M\n" +
	"\x15ListSnapshotsResponse\x124\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x16.stockyard.v1.SnapshotR\tsnapshots\"V\n" +
	"\x16RestoreSnapshotRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12#\n" +
	"\rsnapshot_name\x18\x02 \x01(\tR\fsnapshotName\"\x19\n" +
	"\x17RestoreSnapshotResponse\"U\n" +
	"\x0eGetLogsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x12\n" +
	"\x04tail\x18\x03 \x01(\x05R\x04tail\"<\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\"\xaf\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12-\n" +
	"\x12tailscale_hostname\x18\x04 \x01(\tR\x11tailscaleHostname\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"stopped_at\x18\x06 \x01(\tR\tstoppedAt\"S\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"`\n" +
	"\x12CreateQueueRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"\x15\n" +
	"\x13CreateQueueResponse\",\n" +
	"\x11ListQueuesRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"E\n" +
	"\x12ListQueuesResponse\x12/\n" +
	"\x06queues\x18\x01 \x03(\v2\x17.stockyard.v1.QueueInfoR\x06queues\"O\n" +
	"\x15GetQueueStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\"~\n" +
	"\x16GetQueueStatusResponse\x12-\n" +
	"\x05queue\x18\x01 \x01(\v2\x17.stockyard.v1.QueueInfoR\x05queue\x125\n" +
	"\bcommands\x18\x02 \x03(\v2\x19.stockyard.v1.CommandInfoR\bcommands\"K\n" +
	"\x11FlushQueueRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\"\x14\n" +
	"\x12FlushQueueResponse\"M\n" +
	"\x13DestroyQueueRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\"\x16\n" +
	"\x14DestroyQueueResponse\"\x85\x02\n" +
	"\x13QueueCommandRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12<\n" +
	"\x03env\x18\x04 \x03(\v2*.stockyard.v1.QueueCommandRequest.EnvEntryR\x03env\x12&\n" +
	"\x0fstop_on_failure\x18\x05 \x01(\bR\rstopOnFailure\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x14QueueCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"8\n" +
	"\x17GetCommandStatusRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"O\n" +
	"\x18GetCommandStatusResponse\x123\n" +
	"\acommand\x18\x01 \x01(\v2\x19.stockyard.v1.CommandInfoR\acommand\"S\n" +
	"\x1aStreamCommandOutputRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"(\n" +
	"\x12CommandOutputChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"i\n" +
	"\tQueueInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1c\n" +
	"\tprotected\x18\x03 \x01(\bR\tprotected\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x92\x02\n" +
	"\vCommandInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12&\n" +
	"\x0fstop_on_failure\x18\x06 \x01(\bR\rstopOnFailure\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\t \x01(\tR\n" +
	"finishedAt2\x88\f\n" +
	"\tStockyard\x12O\n" +
	"\n" +
	"CreateTask\x12\x1f.stockyard.v1.CreateTaskRequest\x1a .stockyard.v1.CreateTaskResponse\x12F\n" +
	"\aGetTask\x12\x1c.stockyard.v1.GetTaskRequest\x1a\x1d.stockyard.v1.GetTaskResponse\x12L\n" +
	"\tListTasks\x12\x1e.stockyard.v1.ListTasksRequest\x1a\x1f.stockyard.v1.ListTasksResponse\x12I\n" +
	"\bStopTask\x12\x1d.stockyard.v1.StopTaskRequest\x1a\x1e.stockyard.v1.StopTaskResponse\x12R\n" +
	"\vRestartTask\x12 .stockyard.v1.RestartTaskRequest\x1a!.stockyard.v1.RestartTaskResponse\x12R\n" +
	"\vDestroyTask\x12 .stockyard.v1.DestroyTaskRequest\x1a!.stockyard.v1.DestroyTaskResponse\x12[\n" +
	"\x0eCreateSnapshot\x12#.stockyard.v1.CreateSnapshotRequest\x1a$.stockyard.v1.CreateSnapshotResponse\x12X\n" +
	"\rListSnapshots\x12\".stockyard.v1.ListSnapshotsRequest\x1a#.stockyard.v1.ListSnapshotsResponse\x12^\n" +
	"\x0fRestoreSnapshot\x12$.stockyard.v1.RestoreSnapshotRequest\x1a%.stockyard.v1.RestoreSnapshotResponse\x12A\n" +
	"\aGetLogs\x12\x1c.stockyard.v1.GetLogsRequest\x1a\x16.stockyard.v1.LogEntry0\x01\x12R\n" +
	"\vCreateQueue\x12 .stockyard.v1.CreateQueueRequest\x1a!.stockyard.v1.CreateQueueResponse\x12O\n" +
	"\n" +
	"ListQueues\x12\x1f.stockyard.v1.ListQueuesRequest\x1a .stockyard.v1.ListQueuesResponse\x12[\n" +
	"\x0eGetQueueStatus\x12#.stockyard.v1.GetQueueStatusRequest\x1a$.stockyard.v1.GetQueueStatusResponse\x12O\n" +
	"\n" +
	"FlushQueue\x12\x1f.stockyard.v1.FlushQueueRequest\x1a .stockyard.v1.FlushQueueResponse\x12U\n" +
	"\fDestroyQueue\x12!.stockyard.v1.DestroyQueueRequest\x1a\".stockyard.v1.DestroyQueueResponse\x12U\n" +
	"\fQueueCommand\x12!.stockyard.v1.QueueCommandRequest\x1a\".stockyard.v1.QueueCommandResponse\x12a\n" +
	"\x10GetCommandStatus\x12%.stockyard.v1.GetCommandStatusRequest\x1a&.stockyard.v1.GetCommandStatusResponse\x12c\n" +
	"\x13StreamCommandOutput\x12(.stockyard.v1.StreamCommandOutputRequest\x1a .stockyard.v1.CommandOutputChunk0\x01B&Z$github.com/obra/stockyard/pkg/api/v1b\x06proto3"

var (
	file_api_stockyard_proto_rawDescOnce sync.Once
	file_api_stockyard_proto_rawDescData []byte
)

func file_api_stockyard_proto_rawDescGZIP() []byte {
	file_api_stockyard_proto_rawDescOnce.Do(func() {
		file_api_stockyard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stockyard_proto_rawDesc), len(file_api_stockyard_proto_rawDesc)))
	})
	return file_api_stockyard_proto_rawDescData
}

var file_api_stockyard_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_api_stockyard_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),          // 0: stockyard.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),         // 1: stockyard.v1.CreateTaskResponse
	(*GetTaskRequest)(nil),             // 2: stockyard.v1.GetTaskRequest
	(*GetTaskResponse)(nil),            // 3: stockyard.v1.GetTaskResponse
	(*ListTasksRequest)(nil),           // 4: stockyard.v1.ListTasksRequest
	(*ListTasksResponse)(nil),          // 5: stockyard.v1.ListTasksResponse
	(*StopTaskRequest)(nil),            // 6: stockyard.v1.StopTaskRequest
	(*StopTaskResponse)(nil),           // 7: stockyard.v1.StopTaskResponse
	(*RestartTaskRequest)(nil),         // 8: stockyard.v1.RestartTaskRequest
	(*RestartTaskResponse)(nil),        // 9: stockyard.v1.RestartTaskResponse
	(*DestroyTaskRequest)(nil),         // 10: stockyard.v1.DestroyTaskRequest
	(*DestroyTaskResponse)(nil),        // 11: stockyard.v1.DestroyTaskResponse
	(*CreateSnapshotRequest)(nil),      // 12: stockyard.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),     // 13: stockyard.v1.CreateSnapshotResponse
	(*ListSnapshotsRequest)(nil),       // 14: stockyard.v1.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),      // 15: stockyard.v1.ListSnapshotsResponse
	(*RestoreSnapshotRequest)(nil),     // 16: stockyard.v1.RestoreSnapshotRequest
	(*RestoreSnapshotResponse)(nil),    // 17: stockyard.v1.RestoreSnapshotResponse
	(*GetLogsRequest)(nil),             // 18: stockyard.v1.GetLogsRequest
	(*LogEntry)(nil),                   // 19: stockyard.v1.LogEntry
	(*Task)(nil),                       // 20: stockyard.v1.Task
	(*Snapshot)(nil),                   // 21: stockyard.v1.Snapshot
	(*CreateQueueRequest)(nil),         // 22: stockyard.v1.CreateQueueRequest
	(*CreateQueueResponse)(nil),        // 23: stockyard.v1.CreateQueueResponse
	(*ListQueuesRequest)(nil),          // 24: stockyard.v1.ListQueuesRequest
	(*ListQueuesResponse)(nil),         // 25: stockyard.v1.ListQueuesResponse
	(*GetQueueStatusRequest)(nil),      // 26: stockyard.v1.GetQueueStatusRequest
	(*GetQueueStatusResponse)(nil),     // 27: stockyard.v1.GetQueueStatusResponse
	(*FlushQueueRequest)(nil),          // 28: stockyard.v1.FlushQueueRequest
	(*FlushQueueResponse)(nil),         // 29: stockyard.v1.FlushQueueResponse
	(*DestroyQueueRequest)(nil),        // 30: stockyard.v1.DestroyQueueRequest
	(*DestroyQueueResponse)(nil),       // 31: stockyard.v1.DestroyQueueResponse
	(*QueueCommandRequest)(nil),        // 32: stockyard.v1.QueueCommandRequest
	(*QueueCommandResponse)(nil),       // 33: stockyard.v1.QueueCommandResponse
	(*GetCommandStatusRequest)(nil),    // 34: stockyard.v1.GetCommandStatusRequest
	(*GetCommandStatusResponse)(nil),   // 35: stockyard.v1.GetCommandStatusResponse
	(*StreamCommandOutputRequest)(nil), // 36: stockyard.v1.StreamCommandOutputRequest
	(*CommandOutputChunk)(nil),         // 37: stockyard.v1.CommandOutputChunk
	(*QueueInfo)(nil),                  // 38: stockyard.v1.QueueInfo
	(*CommandInfo)(nil),                // 39: stockyard.v1.CommandInfo
	nil,                                // 40: stockyard.v1.CreateTaskRequest.VmEnvEntry
	nil,                                // 41: stockyard.v1.QueueCommandRequest.EnvEntry
}
var file_api_stockyard_proto_depIdxs = []int32{
	40, // 0: stockyard.v1.CreateTaskRequest.vm_env:type_name -> stockyard.v1.CreateTaskRequest.VmEnvEntry
	20, // 1: stockyard.v1.GetTaskResponse.task:type_name -> stockyard.v1.Task
	20, // 2: stockyard.v1.ListTasksResponse.tasks:type_name -> stockyard.v1.Task
	21, // 3: stockyard.v1.ListSnapshotsResponse.snapshots:type_name -> stockyard.v1.Snapshot
	38, // 4: stockyard.v1.ListQueuesResponse.queues:type_name -> stockyard.v1.QueueInfo
	38, // 5: stockyard.v1.GetQueueStatusResponse.queue:type_name -> stockyard.v1.QueueInfo
	39, // 6: stockyard.v1.GetQueueStatusResponse.commands:type_name -> stockyard.v1.CommandInfo
	41, // 7: stockyard.v1.QueueCommandRequest.env:type_name -> stockyard.v1.QueueCommandRequest.EnvEntry
	39, // 8: stockyard.v1.GetCommandStatusResponse.command:type_name -> stockyard.v1.CommandInfo
	0,  // 9: stockyard.v1.Stockyard.CreateTask:input_type -> stockyard.v1.CreateTaskRequest
	2,  // 10: stockyard.v1.Stockyard.GetTask:input_type -> stockyard.v1.GetTaskRequest
	4,  // 11: stockyard.v1.Stockyard.ListTasks:input_type -> stockyard.v1.ListTasksRequest
	6,  // 12: stockyard.v1.Stockyard.StopTask:input_type -> stockyard.v1.StopTaskRequest
	8,  // 13: stockyard.v1.Stockyard.RestartTask:input_type -> stockyard.v1.RestartTaskRequest
	10, // 14: stockyard.v1.Stockyard.DestroyTask:input_type -> stockyard.v1.DestroyTaskRequest
	12, // 15: stockyard.v1.Stockyard.CreateSnapshot:input_type -> stockyard.v1.CreateSnapshotRequest
	14, // 16: stockyard.v1.Stockyard.ListSnapshots:input_type -> stockyard.v1.ListSnapshotsRequest
	16, // 17: stockyard.v1.Stockyard.RestoreSnapshot:input_type -> stockyard.v1.RestoreSnapshotRequest
	18, // 18: stockyard.v1.Stockyard.GetLogs:input_type -> stockyard.v1.GetLogsRequest
	22, // 19: stockyard.v1.Stockyard.CreateQueue:input_type -> stockyard.v1.CreateQueueRequest
	24, // 20: stockyard.v1.Stockyard.ListQueues:input_type -> stockyard.v1.ListQueuesRequest
	26, // 21: stockyard.v1.Stockyard.GetQueueStatus:input_type -> stockyard.v1.GetQueueStatusRequest
	28, // 22: stockyard.v1.Stockyard.FlushQueue:input_type -> stockyard.v1.FlushQueueRequest
	30, // 23: stockyard.v1.Stockyard.DestroyQueue:input_type -> stockyard.v1.DestroyQueueRequest
	32, // 24: stockyard.v1.Stockyard.QueueCommand:input_type -> stockyard.v1.QueueCommandRequest
	34, // 25: stockyard.v1.Stockyard.GetCommandStatus:input_type -> stockyard.v1.GetCommandStatusRequest
	36, // 26: stockyard.v1.Stockyard.StreamCommandOutput:input_type -> stockyard.v1.StreamCommandOutputRequest
	1,  // 27: stockyard.v1.Stockyard.CreateTask:output_type -> stockyard.v1.CreateTaskResponse
	3,  // 28: stockyard.v1.Stockyard.GetTask:output_type -> stockyard.v1.GetTaskResponse
	5,  // 29: stockyard.v1.Stockyard.ListTasks:output_type -> stockyard.v1.ListTasksResponse
	7,  // 30: stockyard.v1.Stockyard.StopTask:output_type -> stockyard.v1.StopTaskResponse
	9,  // 31: stockyard.v1.Stockyard.RestartTask:output_type -> stockyard.v1.RestartTaskResponse
	11, // 32: stockyard.v1.Stockyard.DestroyTask:output_type -> stockyard.v1.DestroyTaskResponse
	13, // 33: stockyard.v1.Stockyard.CreateSnapshot:output_type -> stockyard.v1.CreateSnapshotResponse
	15, // 34: stockyard.v1.Stockyard.ListSnapshots:output_type -> stockyard.v1.ListSnapshotsResponse
	17, // 35: stockyard.v1.Stockyard.RestoreSnapshot:output_type -> stockyard.v1.RestoreSnapshotResponse
	19, // 36: stockyard.v1.Stockyard.GetLogs:output_type -> stockyard.v1.LogEntry
	23, // 37: stockyard.v1.Stockyard.CreateQueue:output_type -> stockyard.v1.CreateQueueResponse
	25, // 38: stockyard.v1.Stockyard.ListQueues:output_type -> stockyard.v1.ListQueuesResponse
	27, // 39: stockyard.v1.Stockyard.GetQueueStatus:output_type -> stockyard.v1.GetQueueStatusResponse
	29, // 40: stockyard.v1.Stockyard.FlushQueue:output_type -> stockyard.v1.FlushQueueResponse
	31, // 41: stockyard.v1.Stockyard.DestroyQueue:output_type -> stockyard.v1.DestroyQueueResponse
	33, // 42: stockyard.v1.Stockyard.QueueCommand:output_type -> stockyard.v1.QueueCommandResponse
	35, // 43: stockyard.v1.Stockyard.GetCommandStatus:output_type -> stockyard.v1.GetCommandStatusResponse
	37, // 44: stockyard.v1.Stockyard.StreamCommandOutput:output_type -> stockyard.v1.CommandOutputChunk
	27, // [27:45] is the sub-list for method output_type
	9,  // [9:27] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_stockyard_proto_init() }
func file_api_stockyard_proto_init() {
	if File_api_stockyard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stockyard_proto_rawDesc), len(file_api_stockyard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stockyard_proto_goTypes,
		DependencyIndexes: file_api_stockyard_proto_depIdxs,
		MessageInfos:      file_api_stockyard_proto_msgTypes,
	}.Build()
	File_api_stockyard_proto = out.File
	file_api_stockyard_proto_goTypes = nil
	file_api_stockyard_proto_depIdxs = nil
}
