// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/stockyard.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stockyard_CreateTask_FullMethodName          = "/stockyard.v1.Stockyard/CreateTask"
	Stockyard_GetTask_FullMethodName             = "/stockyard.v1.Stockyard/GetTask"
	Stockyard_ListTasks_FullMethodName           = "/stockyard.v1.Stockyard/ListTasks"
	Stockyard_StopTask_FullMethodName            = "/stockyard.v1.Stockyard/StopTask"
	Stockyard_RestartTask_FullMethodName         = "/stockyard.v1.Stockyard/RestartTask"
	Stockyard_DestroyTask_FullMethodName         = "/stockyard.v1.Stockyard/DestroyTask"
	Stockyard_CreateSnapshot_FullMethodName      = "/stockyard.v1.Stockyard/CreateSnapshot"
	Stockyard_ListSnapshots_FullMethodName       = "/stockyard.v1.Stockyard/ListSnapshots"
	Stockyard_RestoreSnapshot_FullMethodName     = "/stockyard.v1.Stockyard/RestoreSnapshot"
	Stockyard_GetLogs_FullMethodName             = "/stockyard.v1.Stockyard/GetLogs"
	Stockyard_CreateQueue_FullMethodName         = "/stockyard.v1.Stockyard/CreateQueue"
	Stockyard_ListQueues_FullMethodName          = "/stockyard.v1.Stockyard/ListQueues"
	Stockyard_GetQueueStatus_FullMethodName      = "/stockyard.v1.Stockyard/GetQueueStatus"
	Stockyard_FlushQueue_FullMethodName          = "/stockyard.v1.Stockyard/FlushQueue"
	Stockyard_ResumeQueue_FullMethodName         = "/stockyard.v1.Stockyard/ResumeQueue"
	Stockyard_DestroyQueue_FullMethodName        = "/stockyard.v1.Stockyard/DestroyQueue"
	Stockyard_QueueCommand_FullMethodName        = "/stockyard.v1.Stockyard/QueueCommand"
	Stockyard_GetCommandStatus_FullMethodName    = "/stockyard.v1.Stockyard/GetCommandStatus"
	Stockyard_StreamCommandOutput_FullMethodName = "/stockyard.v1.Stockyard/StreamCommandOutput"
	Stockyard_StreamQueueOutput_FullMethodName   = "/stockyard.v1.Stockyard/StreamQueueOutput"
)

// StockyardClient is the client API for Stockyard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockyardClient interface {
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error)
	RestartTask(ctx context.Context, in *RestartTaskRequest, opts ...grpc.CallOption) (*RestartTaskResponse, error)
	DestroyTask(ctx context.Context, in *DestroyTaskRequest, opts ...grpc.CallOption) (*DestroyTaskResponse, error)
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error)
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// Queue management
	CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error)
	ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error)
	GetQueueStatus(ctx context.Context, in *GetQueueStatusRequest, opts ...grpc.CallOption) (*GetQueueStatusResponse, error)
	FlushQueue(ctx context.Context, in *FlushQueueRequest, opts ...grpc.CallOption) (*FlushQueueResponse, error)
	ResumeQueue(ctx context.Context, in *ResumeQueueRequest, opts ...grpc.CallOption) (*ResumeQueueResponse, error)
	DestroyQueue(ctx context.Context, in *DestroyQueueRequest, opts ...grpc.CallOption) (*DestroyQueueResponse, error)
	// Command execution
	QueueCommand(ctx context.Context, in *QueueCommandRequest, opts ...grpc.CallOption) (*QueueCommandResponse, error)
	GetCommandStatus(ctx context.Context, in *GetCommandStatusRequest, opts ...grpc.CallOption) (*GetCommandStatusResponse, error)
	StreamCommandOutput(ctx context.Context, in *StreamCommandOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandOutputChunk], error)
	StreamQueueOutput(ctx context.Context, in *StreamQueueOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueueOutputChunk], error)
}

type stockyardClient struct {
	cc grpc.ClientConnInterface
}

func NewStockyardClient(cc grpc.ClientConnInterface) StockyardClient {
	return &stockyardClient{cc}
}

func (c *stockyardClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, Stockyard_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, Stockyard_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, Stockyard_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTaskResponse)
	err := c.cc.Invoke(ctx, Stockyard_StopTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) RestartTask(ctx context.Context, in *RestartTaskRequest, opts ...grpc.CallOption) (*RestartTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartTaskResponse)
	err := c.cc.Invoke(ctx, Stockyard_RestartTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) DestroyTask(ctx context.Context, in *DestroyTaskRequest, opts ...grpc.CallOption) (*DestroyTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyTaskResponse)
	err := c.cc.Invoke(ctx, Stockyard_DestroyTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, Stockyard_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, Stockyard_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreSnapshotResponse)
	err := c.cc.Invoke(ctx, Stockyard_RestoreSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stockyard_ServiceDesc.Streams[0], Stockyard_GetLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stockyard_GetLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *stockyardClient) CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQueueResponse)
	err := c.cc.Invoke(ctx, Stockyard_CreateQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQueuesResponse)
	err := c.cc.Invoke(ctx, Stockyard_ListQueues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) GetQueueStatus(ctx context.Context, in *GetQueueStatusRequest, opts ...grpc.CallOption) (*GetQueueStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueueStatusResponse)
	err := c.cc.Invoke(ctx, Stockyard_GetQueueStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) FlushQueue(ctx context.Context, in *FlushQueueRequest, opts ...grpc.CallOption) (*FlushQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushQueueResponse)
	err := c.cc.Invoke(ctx, Stockyard_FlushQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) ResumeQueue(ctx context.Context, in *ResumeQueueRequest, opts ...grpc.CallOption) (*ResumeQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeQueueResponse)
	err := c.cc.Invoke(ctx, Stockyard_ResumeQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) DestroyQueue(ctx context.Context, in *DestroyQueueRequest, opts ...grpc.CallOption) (*DestroyQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyQueueResponse)
	err := c.cc.Invoke(ctx, Stockyard_DestroyQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) QueueCommand(ctx context.Context, in *QueueCommandRequest, opts ...grpc.CallOption) (*QueueCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueCommandResponse)
	err := c.cc.Invoke(ctx, Stockyard_QueueCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) GetCommandStatus(ctx context.Context, in *GetCommandStatusRequest, opts ...grpc.CallOption) (*GetCommandStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommandStatusResponse)
	err := c.cc.Invoke(ctx, Stockyard_GetCommandStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockyardClient) StreamCommandOutput(ctx context.Context, in *StreamCommandOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandOutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stockyard_ServiceDesc.Streams[1], Stockyard_StreamCommandOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamCommandOutputRequest, CommandOutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stockyard_StreamCommandOutputClient = grpc.ServerStreamingClient[CommandOutputChunk]

func (c *stockyardClient) StreamQueueOutput(ctx context.Context, in *StreamQueueOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueueOutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stockyard_ServiceDesc.Streams[2], Stockyard_StreamQueueOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamQueueOutputRequest, QueueOutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stockyard_StreamQueueOutputClient = grpc.ServerStreamingClient[QueueOutputChunk]

// StockyardServer is the server API for Stockyard service.
// All implementations must embed UnimplementedStockyardServer
// for forward compatibility.
type StockyardServer interface {
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error)
	RestartTask(context.Context, *RestartTaskRequest) (*RestartTaskResponse, error)
	DestroyTask(context.Context, *DestroyTaskRequest) (*DestroyTaskResponse, error)
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error)
	GetLogs(*GetLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	// Queue management
	CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error)
	ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error)
	GetQueueStatus(context.Context, *GetQueueStatusRequest) (*GetQueueStatusResponse, error)
	FlushQueue(context.Context, *FlushQueueRequest) (*FlushQueueResponse, error)
	ResumeQueue(context.Context, *ResumeQueueRequest) (*ResumeQueueResponse, error)
	DestroyQueue(context.Context, *DestroyQueueRequest) (*DestroyQueueResponse, error)
	// Command execution
	QueueCommand(context.Context, *QueueCommandRequest) (*QueueCommandResponse, error)
	GetCommandStatus(context.Context, *GetCommandStatusRequest) (*GetCommandStatusResponse, error)
	StreamCommandOutput(*StreamCommandOutputRequest, grpc.ServerStreamingServer[CommandOutputChunk]) error
	StreamQueueOutput(*StreamQueueOutputRequest, grpc.ServerStreamingServer[QueueOutputChunk]) error
	mustEmbedUnimplementedStockyardServer()
}

// UnimplementedStockyardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockyardServer struct{}

func (UnimplementedStockyardServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedStockyardServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedStockyardServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedStockyardServer) StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTask not implemented")
}
func (UnimplementedStockyardServer) RestartTask(context.Context, *RestartTaskRequest) (*RestartTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartTask not implemented")
}
func (UnimplementedStockyardServer) DestroyTask(context.Context, *DestroyTaskRequest) (*DestroyTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyTask not implemented")
}
func (UnimplementedStockyardServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedStockyardServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedStockyardServer) RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreSnapshot not implemented")
}
func (UnimplementedStockyardServer) GetLogs(*GetLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedStockyardServer) CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQueue not implemented")
}
func (UnimplementedStockyardServer) ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQueues not implemented")
}
func (UnimplementedStockyardServer) GetQueueStatus(context.Context, *GetQueueStatusRequest) (*GetQueueStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueueStatus not implemented")
}
func (UnimplementedStockyardServer) FlushQueue(context.Context, *FlushQueueRequest) (*FlushQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushQueue not implemented")
}
func (UnimplementedStockyardServer) ResumeQueue(context.Context, *ResumeQueueRequest) (*ResumeQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeQueue not implemented")
}
func (UnimplementedStockyardServer) DestroyQueue(context.Context, *DestroyQueueRequest) (*DestroyQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyQueue not implemented")
}
func (UnimplementedStockyardServer) QueueCommand(context.Context, *QueueCommandRequest) (*QueueCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueueCommand not implemented")
}
func (UnimplementedStockyardServer) GetCommandStatus(context.Context, *GetCommandStatusRequest) (*GetCommandStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommandStatus not implemented")
}
func (UnimplementedStockyardServer) StreamCommandOutput(*StreamCommandOutputRequest, grpc.ServerStreamingServer[CommandOutputChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamCommandOutput not implemented")
}
func (UnimplementedStockyardServer) StreamQueueOutput(*StreamQueueOutputRequest, grpc.ServerStreamingServer[QueueOutputChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamQueueOutput not implemented")
}
func (UnimplementedStockyardServer) mustEmbedUnimplementedStockyardServer() {}
func (UnimplementedStockyardServer) testEmbeddedByValue()                   {}

// UnsafeStockyardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockyardServer will
// result in compilation errors.
type UnsafeStockyardServer interface {
	mustEmbedUnimplementedStockyardServer()
}

func RegisterStockyardServer(s grpc.ServiceRegistrar, srv StockyardServer) {
	// If the following call panics, it indicates UnimplementedStockyardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stockyard_ServiceDesc, srv)
}

func _Stockyard_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_StopTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).StopTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_StopTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).StopTask(ctx, req.(*StopTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_RestartTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).RestartTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_RestartTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).RestartTask(ctx, req.(*RestartTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_DestroyTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).DestroyTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_DestroyTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).DestroyTask(ctx, req.(*DestroyTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_RestoreSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).RestoreSnapshot(ctx, req.(*RestoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_GetLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockyardServer).GetLogs(m, &grpc.GenericServerStream[GetLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stockyard_GetLogsServer = grpc.ServerStreamingServer[LogEntry]

func _Stockyard_CreateQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).CreateQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_CreateQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).CreateQueue(ctx, req.(*CreateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_ListQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).ListQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_ListQueues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).ListQueues(ctx, req.(*ListQueuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_GetQueueStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).GetQueueStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_GetQueueStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).GetQueueStatus(ctx, req.(*GetQueueStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_FlushQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).FlushQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_FlushQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).FlushQueue(ctx, req.(*FlushQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_ResumeQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).ResumeQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_ResumeQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).ResumeQueue(ctx, req.(*ResumeQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_DestroyQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).DestroyQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_DestroyQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).DestroyQueue(ctx, req.(*DestroyQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_QueueCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).QueueCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_QueueCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).QueueCommand(ctx, req.(*QueueCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_GetCommandStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommandStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockyardServer).GetCommandStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stockyard_GetCommandStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockyardServer).GetCommandStatus(ctx, req.(*GetCommandStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stockyard_StreamCommandOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCommandOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockyardServer).StreamCommandOutput(m, &grpc.GenericServerStream[StreamCommandOutputRequest, CommandOutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stockyard_StreamCommandOutputServer = grpc.ServerStreamingServer[CommandOutputChunk]

func _Stockyard_StreamQueueOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamQueueOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockyardServer).StreamQueueOutput(m, &grpc.GenericServerStream[StreamQueueOutputRequest, QueueOutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stockyard_StreamQueueOutputServer = grpc.ServerStreamingServer[QueueOutputChunk]

// Stockyard_ServiceDesc is the grpc.ServiceDesc for Stockyard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stockyard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stockyard.v1.Stockyard",
	HandlerType: (*StockyardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _Stockyard_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Stockyard_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Stockyard_ListTasks_Handler,
		},
		{
			MethodName: "StopTask",
			Handler:    _Stockyard_StopTask_Handler,
		},
		{
			MethodName: "RestartTask",
			Handler:    _Stockyard_RestartTask_Handler,
		},
		{
			MethodName: "DestroyTask",
			Handler:    _Stockyard_DestroyTask_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _Stockyard_CreateSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _Stockyard_ListSnapshots_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _Stockyard_RestoreSnapshot_Handler,
		},
		{
			MethodName: "CreateQueue",
			Handler:    _Stockyard_CreateQueue_Handler,
		},
		{
			MethodName: "ListQueues",
			Handler:    _Stockyard_ListQueues_Handler,
		},
		{
			MethodName: "GetQueueStatus",
			Handler:    _Stockyard_GetQueueStatus_Handler,
		},
		{
			MethodName: "FlushQueue",
			Handler:    _Stockyard_FlushQueue_Handler,
		},
		{
			MethodName: "ResumeQueue",
			Handler:    _Stockyard_ResumeQueue_Handler,
		},
		{
			MethodName: "DestroyQueue",
			Handler:    _Stockyard_DestroyQueue_Handler,
		},
		{
			MethodName: "QueueCommand",
			Handler:    _Stockyard_QueueCommand_Handler,
		},
		{
			MethodName: "GetCommandStatus",
			Handler:    _Stockyard_GetCommandStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLogs",
			Handler:       _Stockyard_GetLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCommandOutput",
			Handler:       _Stockyard_StreamCommandOutput_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamQueueOutput",
			Handler:       _Stockyard_StreamQueueOutput_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/stockyard.proto",
}
